#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
. "$SCRIPT_DIR"/../../paths

set_context_env_vars

run cp --recursive "$CONTEXT_SOURCE_DIR"/{Dockerfile,buildscripts} .
run cp "$CONTEXT_SOURCE_DIR"/{glibc-2.26,binutils-2.29,attr-2.4.47,inetutils-1.9.4}-disable-broken-tests.patch .
run cp "$CONTEXT_SOURCE_DIR"/perl-5.26.0-upstream-docker-fix.patch .

run docker build --build-arg=GIT_BRANCH="$GIT_BRANCH" \
                 --build-arg=TAG_BASE="$TAG_BASE"     \
                 --tag="$CONTEXT_TAG"                 \
                 .
