#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
. "$SCRIPT_DIR"/../../paths

set_context_env_vars

run cp --recursive "$CONTEXT_SOURCE_DIR"/{Dockerfile,buildscripts,glibc-2.26-disable-broken-tests.patch} .
run cp "$CONTEXT_SOURCE_DIR"/binutils-2.29-disable-broken-tests.patch .
# NOTE: Assuming these failures are due to running in docker for now.
run cp "$CONTEXT_SOURCE_DIR"/attr-2.4.47-disable-broken-tests.patch .

run cp "$CONTEXT_SOURCE_DIR"/libtool-2.4.6-disable-broken-tests.patch .

run docker build --build-arg=GIT_BRANCH="$GIT_BRANCH" \
                 --build-arg=TAG_BASE="$TAG_BASE"     \
                 --tag="$CONTEXT_TAG"                 \
                 .
