#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
source "$SCRIPT_DIR"/../../paths

set_context_env_vars

#               --env=container_uuid=
#               --security-opt=seccomp=unconfined         \
#               --cap-add=SYS_ADMIN                       \
run docker run --rm                                      \
               --tmpfs=/tmp                              \
               --tmpfs=/run                              \
               --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
               --interactive                             \
               --tty                                     \
               --env=TERM                                \
               --env=COLORTERM                           \
               --env=container=docker                    \
               --stop-signal=SIGRTMIN+3                  \
               "$CONTEXT_TAG"
