#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
. "$SCRIPT_DIR"/../../paths

set_context_env_vars

run cp --recursive "$CONTEXT_SOURCE_DIR"/Dockerfile  \
                   "$CONTEXT_SOURCE_DIR"/apt-offline \
                   "$CONTEXT_THIRDPARTY_DIR"/*.deb .

run docker build --build-arg=GIT_BRANCH="$GIT_BRANCH" \
                 --build-arg=TAG_BASE="$TAG_BASE"     \
                 --tag="$CONTEXT_TAG"                 \
                 .
