#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}"/images/common

for docker_image_source in $(getDockerImageSources); do
  parent_image_source="$(getParentDockerImageSource "${docker_image_source}")"
  if [[ -z "${parent_image_source}" ]]; then
    echo "${docker_image_source}"
  else
    echo "${docker_image_source}" "$(dirname "${parent_image_source}")"
  fi
done