#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
. "$SCRIPT_DIR"/../paths

for context in ubuntu-core \
               apt-offline \
               lfs-host-toolchain; do
	run mkdir --parents "$context"
	run cd              "$context"
	
	run "$SCRIPT_DIR/$context"/build
	
	run cd ..
done
