#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail
shopt -s inherit_errexit
shopt -s nullglob

SCRIPT_NAME="$(basename      "${BASH_SOURCE[0]}")"
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME
readonly SCRIPT_PATH

readonly PACKAGE="$1";       shift
readonly OPERATION="${1:-}"; shift || true

. "$HOME"/buildscripts/common

enter_build_env ()
{
	cd "$PACKAGE"
	
	export CFLAGS='-Os -pipe'
	export CXXFLAGS="$CFLAGS"
	 export SOURCES
}

readonly BUILDSCRIPT="$SCRIPT_PATH/$PACKAGE"
readonly BUILD_LOG_PREFIX="$HOME/$PACKAGE"-build

cd "${LFS:-$HOME}"/build

if [[ $OPERATION == prepare ]]; then
  mkdir --parents "$PACKAGE"
  
  readonly ARCHIVE="$SOURCES/$1"
	echo "Unpacking $ARCHIVE"
	tar --extract --strip-components=1 --directory="$PACKAGE" --file="$ARCHIVE"
else
	enter_build_env
	if [[ -z $OPERATION ]]; then
		"$BUILDSCRIPT" >> "$BUILD_LOG_PREFIX.log" 2>&1
	else
    build_log="$BUILD_LOG_PREFIX-$OPERATION.log"
    echo "Building $PACKAGE $OPERATION" >> "$build_log" 2>&1
		"$BUILDSCRIPT" "$BUILDSCRIPT-$OPERATION" >> "$BUILD_LOG_PREFIX-$OPERATION.log" 2>&1
	fi
fi
