#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

add_x10 ()
{
  local -r A="$1"
  local -r B="$2"
  
  local -i A_X10; A_X10="$(get_x10 "$A")"; readonly A_X10
  local -i B_X10; B_X10="$(get_x10 "$B")"; readonly B_X10
  
  local -i RETVAL_X10; RETVAL_X10="$((A_X10 + B_X10))"; readonly RETVAL_X10

  get_div10 "$RETVAL_X10"
}

get_percent ()
{
  local -r P="$1"
  local -r Q="$2"
  
  local -i P_X10; P_X10="$(get_x10 "$P")"; readonly P_X10
  local -i Q_X10; Q_X10="$(get_x10 "$Q")"; readonly Q_X10
  
  # Note: Multiplying by 1,000 instead of 100 because everything is X10.
  local -i RETVAL_X10; RETVAL_X10="$((P_X10 * 1000 / Q_X10))"; readonly RETVAL_X10

  get_div10 "$RETVAL_X10"
}

get_dhms ()
{
	local -ri EPOCH_SECONDS="$1"
	
	local -ri DAYS=$((   EPOCH_SECONDS / 60 / 60 / 24))
	local -ri HOURS=$((  EPOCH_SECONDS / 60 / 60 % 24))
	local -ri MINUTES=$((EPOCH_SECONDS / 60      % 60))
	local -ri SECONDS=$((EPOCH_SECONDS           % 60))
	
	if ((DAYS > 0)); then
		echo -n "${DAYS}d "
	fi
	
	printf '%02d:%02d:%02d' "$HOURS" "$MINUTES" "$SECONDS"
}

get_div10 ()
{
	local -r VALUE="$1"
	
	local retval
	if ((${#VALUE} == 0)); then
		echo 0
	elif ((${#VALUE} == 1)); then
		echo 0."$VALUE"
	else
		echo "${VALUE:0:-1}.${VALUE: -1}"
	fi
}

get_package_sbus ()
{
	local -r PACKAGE_PATH="$1"
	
  local -i retval_x10
  retval_x10="$(get_script_sbus_x10 "$PACKAGE_PATH")"

  local -i script_sbus_x10
  for stage_script in "$PACKAGE_PATH"-[0-9]-*; do
    local script_sbus_x10
    script_sbus_x10="$(get_script_sbus_x10 "$stage_script")"
    retval_x10=$((retval_x10 + script_sbus_x10))
  done
  
  get_div10 "$retval_x10"
}

get_script_sbus ()
{
  local -r _SCRIPT_PATH="$1"
  
  sed -rn 's/^# SBUS: //p' "$_SCRIPT_PATH"
}

get_script_sbus_x10 ()
{
  local -r _SCRIPT_PATH="$1"

  local _SBUS="$(get_script_sbus "$_SCRIPT_PATH")"
  
  get_x10 "$_SBUS"
}

get_total_sbus ()
{
	local -r BUILDSCRIPTS_DIR="$1"
	
	local retval_x10=0
	for script_path in "$BUILDSCRIPTS_DIR"/*-*-[0-9]-*; do
		local script_sbus
		local script_sbus_x10
	  script_sbus="$(get_script_sbus "$script_path")"
		script_sbus_x10="$(get_x10 "$script_sbus")"
		retval_x10=$((script_sbus_x10 + retval_x10))
	done
	get_div10 "$retval_x10"
}

get_x10 ()
{
	local -r VALUE="$1"
	
	if [[ "$VALUE" == *.* ]]; then
		echo $((10#${VALUE/./}))
	else
		echo "$VALUE"0
	fi
}
