#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
. "$SCRIPT_DIR"/../../paths

set_context_env_vars

run cp --recursive "$CONTEXT_SOURCE_DIR"/{Dockerfile,buildscripts,etc,lfs_home,root_home} .
run cp --recursive "$THIRDPARTY_DIR"/lfs/sources . 

run docker build --build-arg=GIT_BRANCH="$GIT_BRANCH"   \
                 --build-arg=TAG_BASE="$TAG_BASE"       \
                 --tag="$CONTEXT_TAG-cache"             \
                 --target=staging                       \
                 .

run docker build --build-arg=GIT_BRANCH="$GIT_BRANCH"   \
                 --build-arg=TAG_BASE="$TAG_BASE"       \
                 --tag="$CONTEXT_TAG"                   \
                 .
