#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}"/../common

docker build --tag "${DOCKER_IMAGE}":"${DOCKER_TAG}" "${SCRIPT_DIR}"
