#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}"/../common

docker tag "${IMAGE_NAME}" "${AWS_IMAGE_NAME}"
docker push "${AWS_IMAGE_NAME}"
