#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

readonly TAG_BASE="$1"
readonly CONTEXT="$2"
readonly GIT_BRANCH="$3"

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_PATH
. "$SCRIPT_PATH"/buildscripts/common

get_total_sbus ()
{
	local retval_x10=0
	for package_path in "$SCRIPT_PATH"/buildscripts/*-*; do
		local package_sbus
		local package_sbus_x10
		package_sbus="$(get_package_sbus "$package_path")"
		package_sbus_x10="$(get_x10 "$package_sbus")"
		retval_x10=$((package_sbus_x10 + $retval_x10))
	done
	get_div10 "$retval_x10"
}

TOTAL_SBUS_FILE="$SCRIPT_PATH"/lfs_home/total_sbus
TOTAL_SBUS="$(get_total_sbus)"; readonly TOTAL_SBUS
OLD_SBUS="$(cat "$TOTAL_SBUS_FILE" 2>/dev/null || echo 0)"
if [[ "$TOTAL_SBUS" != "$OLD_SBUS" ]]; then
	echo "$TOTAL_SBUS" > "$TOTAL_SBUS_FILE"
fi

docker build --build-arg=GIT_BRANCH="$GIT_BRANCH" \
             --build-arg=TAG_BASE="$TAG_BASE"     \
             --tag="$TAG_BASE/$CONTEXT"           \
             "$SCRIPT_PATH"
