#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

readonly TAG_BASE="$1"
readonly CONTEXT="$2"
readonly GIT_BRANCH="$3"

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_PATH
. "$SCRIPT_PATH"/buildscripts/common

TOTAL_SBUS_FILE="$SCRIPT_PATH"/lfs_home/total_sbus
TOTAL_SBUS="$(get_total_sbus "$SCRIPT_PATH"/buildscripts)"; readonly TOTAL_SBUS
OLD_SBUS="$(cat "$TOTAL_SBUS_FILE" 2>/dev/null || echo 0)"
if [[ "$TOTAL_SBUS" != "$OLD_SBUS" ]]; then
	echo "$TOTAL_SBUS" > "$TOTAL_SBUS_FILE"
fi

docker build --build-arg=GIT_BRANCH="$GIT_BRANCH"   \
             --build-arg=TAG_BASE="$TAG_BASE"       \
             --tag="$TAG_BASE/$CONTEXT:$GIT_BRANCH" \
             "$SCRIPT_PATH"
