#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}"/common 

DIRECTORY="${1}"
if [[ -z "${DIRECTORY}" ]]; then
  echo 'DIRECTORY is required.' 2>&1
  exit 1
fi

export GIT_BRANCH="$(getGitBranch)"
docker build --tag "$(getTaggedDockerImageName "${DIRECTORY}")" "${DIRECTORY}"
