#!/usr/bin/env bash

set -e
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "${SCRIPT_DIR}"/common

DIRECTORY="${1}"; shift
if [[ -z "${DIRECTORY}" ]]; then
  echo 'DIRECTORY is required.' 2>&1
  exit 1
fi

docker_command=(docker run)
docker_command+=(--interactive)
docker_command+=(--tty)
if [[ -x "${DIRECTORY}/extra-docker-args" ]]; then
  docker_command+=($("${DIRECTORY}"/extra-docker-args))
fi
while [[ "${1}" == '--dockerArg' ]]; do
  shift
  docker_command+=("${1}")
  shift
done
docker_command+=(--hostname=$(getDockerImageName "${DIRECTORY}").${DNS_DOMAIN})
docker_command+=("$(getTaggedDockerImageName "${DIRECTORY}")")
docker_command+=("${@}")

exec "${docker_command[@]}"
