#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR
. "$SCRIPT_DIR"/../../paths 

set_context_env_vars

run patch --input="$CONTEXT_SOURCE_DIR"/Dockerfile.patch \
          --output=Dockerfile                            \
          "$CONTEXT_THIRDPARTY_DIR"/Dockerfile
run cp "$CONTEXT_THIRDPARTY_DIR"/ubuntu-xenial-core-cloudimg-amd64-root.tar.gz .

run docker build --tag="$CONTEXT_TAG" .
