#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

readonly TAG_BASE="$1"
readonly CONTEXT="$2"
readonly GIT_BRANCH="$3"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_DIR

docker build --build-arg=GIT_BRANCH="$GIT_BRANCH" \
             --build-arg=TAG_BASE="$TAG_BASE"     \
             --tag="$TAG_BASE/$CONTEXT:$GIT_BRANCH"

