#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

readonly PACKAGE="$1"
readonly ARCHIVE="$2"

SCRIPT_NAME="$(basename      "${BASH_SOURCE[0]}")"
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME
readonly SCRIPT_PATH

get_package_sbus ()
{
  local -r PACKAGE_PATH="$1"

  sed -rn 's/^# SBUS: (.*)/\1/p' "$PACKAGE_PATH"
}

get_total_sbus ()
{
  local retval=0
  for package_path in "$SCRIPT_PATH"/*; do
    local package; package="$(basename "$package_path")"
    if [[ "$package" == build ]]; then
      continue
    fi

    local package_sbus
    package_sbus="$(get_package_sbus "$package_path")"
    retval="$(echo "$retval + $package_sbus" | bc)"
  done

  echo $retval
}

declare -r SBUS_FILE="$HOME"/total_sbus
declare -r BUILDSCRIPT="$SCRIPT_PATH/$PACKAGE"

TOTAL_SBUS="$(get_total_sbus)";                         readonly TOTAL_SBUS
PACKAGE_SBUS="$(get_package_sbus "$BUILDSCRIPT")";      readonly PACKAGE_SBUS
SBU_SECONDS="$(cat "$HOME"/sbu_seconds || echo 0)";     readonly SBU_SECONDS
COMPLETE_SBUS="$(cat "$HOME"/complete_sbus || echo 0)"; readonly COMPLETE_SBUS

cd "$LFS"/sources

echo "Unpacking $ARCHIVE"
mkdir -v "$PACKAGE"
tar --extract  --strip-components=1 --directory="$PACKAGE" --file="$ARCHIVE"

cd "$PACKAGE"
echo "Building $PACKAGE ($PACKAGE_SBUS SBUS)  $COMPLETE_SBUS/$TOTAL_SBUS Complete"
CFLAGS='-Os -pipe' CXXFLAGS='-Os -pipe' "$BUILDSCRIPT" > ~/"$PACKAGE"-build.log
