#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

sudo apt update
sudo apt install curl
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu '"$(lsb_release -cs)"' stable'

sudo apt update
sudo apt install docker-ce=17.09.0~ce-0~ubuntu

sudo usermod --append --groups=docker "$(whoami)"
