#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; declare -r SCRIPT_DIR="${script_dir}"
. "${SCRIPT_DIR}"/../../src/common

IMAGE_NAME="${1}"
if [[ -z "${IMAGE_NAME}" ]]; then
  echo 'IMAGE_NAME is required.' 1>&2
  exit 1
fi

root_home="$(run getImageEnvironmentVariable "${IMAGE_NAME}" 'ROOT_HOME')"; declare -r ROOT_HOME="${root_home}"

echo "--volume=${HOME}/.aws-docker:${ROOT_HOME}/.aws"
