#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

readonly TAG="$1"

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; readonly SCRIPT_PATH

get_package_sbus ()
{
  local -r PACKAGE_PATH="$1"

  sed -rn 's/^# SBUS: (.*)/\1/p' "$PACKAGE_PATH"
}

get_total_sbus ()
{
  local retval=0
  for package_path in "$SCRIPT_PATH"/buildscripts/*-*; do
    local package_sbus
    package_sbus="$(get_package_sbus "$package_path")"
    retval="$(echo "$package_sbus + $retval" | bc)"
  done
  echo "$retval"
}

TOTAL_SBUS_FILE="$SCRIPT_PATH"/lfs_home/total_sbus
TOTAL_SBUS="$(get_total_sbus)"; readonly TOTAL_SBUS
OLD_SBUS="$(cat "$TOTAL_SBUS_FILE" 2>/dev/null || echo 0)"
if [[ "$TOTAL_SBUS" != "$OLD_SBUS" ]]; then
  echo "$TOTAL_SBUS" > "$TOTAL_SBUS_FILE"
fi

docker build --tag="$TAG" "$SCRIPT_PATH"
