#!/usr/bin/env bash

if [[ -z "${PATHS_8djf8sj48jt8sjr8ja4al:-}" ]]; then
	export PATHS_8djf8sj48jt8sjr8ja4al=true
	
	run ()
	{
		echo "Running:$(printf ' %q' "$@")"
		"$@"
	}
	
	set_context_env_vars ()
	{
		CONTEXT_SOURCE_DIR="$SCRIPT_DIR";                       readonly CONTEXT_SOURCE_DIR
		CONTEXT_NAME="$(basename "$CONTEXT_SOURCE_DIR")";       readonly CONTEXT_NAME
		CONTEXT_THIRDPARTY_DIR="$THIRDPARTY_DIR/$CONTEXT_NAME"; readonly CONTEXT_THIRDPARTY_DIR
		CONTEXT_TAG="$TAG_BASE/$CONTEXT_NAME:$GIT_BRANCH";      readonly CONTEXT_TAG
		
		export CONTEXT_NAME
		export CONTEXT_SOURCE_DIR
		export CONTEXT_TAG
		export CONTEXT_THIRDPARTY_DIR
	}
	
	REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel)"; readonly REPO_DIR
	SOURCE_DIR="$REPO_DIR"/src;                                                         readonly SOURCE_DIR
	THIRDPARTY_DIR="$SOURCE_DIR"/thirdparty;                                            readonly THIRDPARTY_DIR
	GIT_BRANCH="$(cd "$REPO_DIR" && git symbolic-ref HEAD)"
	GIT_BRANCH="${GIT_BRANCH##refs/heads/}";                                            readonly GIT_BRANCH
	TAG_BASE=lepertheory;                                                               readonly TAG_BASE
	
	export GIT_BRANCH
	export REPO_DIR
	export SOURCE_DIR
	export TAG_BASE
	export THIRDPARTY_DIR
	
	export -f run
	export -f set_context_env_vars
fi
