#!/usr/bin/env bash

set -e
set -o pipefail

BASHRC="${1}"
if [[ -z "${BASHRC}" ]]; then
  echo 'BASHRC is required.'
  exit 1
fi

apk add --no-cache groff=1.22.3-r1
pip3 install awscli

echo                                                                     >> "${BASHRC}"
echo '# Complete AWS commands with `aws ...`.'                           >> "${BASHRC}"
echo 'complete -C "$(printf '"'"'%q'"'"' "$(which aws_completer)")" aws' >> "${BASHRC}"
